name: Release
on:
  push:
    branches:
      - master
    paths:
      - "frontend"
      - ".github/workflows"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install and Build
        run: |
          cd frontend
          yarn
          yarn build
        env:
          VUE_APP_I18N_LOCALE: zh-hans
          VUE_APP_I18N_FALLBACK_LOCALE: zh-hans
          AL_FE_KEYID: ${{ secrets.AL_FE_KEYID }}
          AL_FE_SECRET: ${{ secrets.AL_FE_SECRET }}
          AL_FE_BUCKET: ${{ secrets.AL_FE_BUCKET }}
          PROJ_NAME: ${{ secrets.PROJ_NAME }}
          FE_DOMAIN: ${{ secrets.FE_DOMAIN }}

          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PWD: ${{ secrets.REMOTE_PWD }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}